inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  TargetRubyVersion: 2.7.4
  Exclude:
    - "**/db/**/*"
    - "**/Gemfile"
    - "**/Gemfile.lock"
    - "**/Guardfile"
    - "**/Rakefile"
    - "**/rails"
    - "**/config/**/*"
    - "**/spec/*"
    - "**/test/**/*"
    - "**/lib/**/*"
    - "**/bin/*"
    - "**/migrate/**/*"
    - "**/vendor/**/*"
    - "**/vendor/**/*"
    - "*"

Rails:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Metrics/LineLength:
  Enabled: false
