AllCops:
  TargetRubyVersion: 3.1.3
  NewCops: enable
  Exclude:
    - 'packages/**/db/**/*'
    - 'packages/**/Gemfile'
    - 'packages/**/Gemfile.lock'
    - 'packages/**/Rakefile'
    - 'packages/**/rails'
    - 'packages/**/lib/**/*'
    - 'packages/**/bin/*'
    - 'packages/**/migrate/**/*'
    - 'packages/**/vendor/**/*'

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
  CountComments: false
  Max: 150

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  CountComments: false
  Max: 50

Metrics/ModuleLength:
  CountComments: false
  Max: 250

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/EvalWithLocation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
